### ISSUE TITLE
Correcties

### ISSUE THREAD

**Issue by andredelft** [johannesdewit/nederlandse-heidegger-bibliografie#1]
Hey, wat cool dat je dit bijhoudt! Ik liep even door het lijstje en had wat opmerkingen:

* Hoewel bij de Lannoo-reeks op de cover inderdaad 'NEDERLANDSE HEIDEGGER BIBLIOTHEEK' staat, wordt er in het werk zelf naar verwezen als het grammaticaal wél correcte 'Nederlandse Heidegger-bibliotheek'.
* Je zegt 'tegenwoordig uitgegeven door Boom' bij Sun en Vantilt, dat geldt strikt gezien natuurlijk alleen voor de werken die nog in druk zijn. Voor bijv. _Over denken, bouwen, wonen_ geldt dat niet.
* _Het beginsel van grond_ was eerder in 2009 al verschenen in een andere reeks bij Boom (die hardcover-reeks met grijze stofomslag, voorloper van de 'Grote klassieken').
* Het publicatiejaar van de vertaling van 'Abraham a Santa Clara' door Samuel IJsseling staat verkeerd op DBNL, het moet 1967 zijn. Zie [dit screenshot](https://github.com/johannesdewit/nederlandse-heidegger-bibliografie/assets/32297879/1861997d-56ad-4ebd-9c58-908288490be9).
* SUN, dat stond voor Socialistische Uitgeverij Nijmegen, schrijf je met hoofdletters.

Maar cool, ik stel voor dat we dit gaan hosten op ons platform! Ik stel me voor dat je verschillende weergaven kunt maken, op jaar, uitgever, vertaler. En dat je nog kunt aangeven welke vertalingen wel en niet gedrukt worden.

**Comment by andredelft** [comment]
We kunnen ook een bredere bibliografie maken, door ook bijv. de proefschriften van IJsseling, Duintjer, Visser e.d. toe te voegen.

**Comment by johannesdewit** [comment]
Hee! Ja, ik had een beginnetje ooit gemaakt en dacht, ik verzamel dat ergens. Bedankt voor je correcties, die waren mij niet opgevallen! 

Mijn idee was om een Zoterogroep bij te houden (de link staat in de <README.md>) en daar een export van te maken en die hier te plaatsen. Dan is het makkelijk te wijzigen en uit te breiden, en gemakkelijk met meerdere mensen aan te werken. De output daarvan zouden we inderdaad op ons platform kunnen hosten, waarbij deze repo zowel backup als autoriteit blijft, omdat ik niet weet hoe de Zoterocommunity met die groepen omgaat.

Verder was het inderdaad ook mijn idee om de verzameling op termijn uit te breiden met andere Nederlandstalige werken over Heidegger.

**Comment by johannesdewit** [comment]
- [x] 'Nederlandse Heidegger-bibliotheek' > 'Nederlandse Heidegger-bibliotheek'
- [ ] 'Tegenwoordig uitgegeven door Boom' bij Sun en Vantilt alleen voor de werken die daadwerkelijk door Boom worden uitgegeven.
- [x] Eerste uitgave van _Het beginsel van grond_ opnemen.
- [ ] Reeks _Grote klassieken_ aan _Het beginsel van grond_ toevoegen.
- [x] Jaartal IJsselings vertaling van _Abraham a santa clara_ naar 1967 veranderen.
- [x] SUN ipv Sun.
